### ISSUE TITLE
some error in tesseract or OCR.py?

### ISSUE THREAD

**Issue by nanomoretti** [arturaugusto/display_ocr#2]
I install python-opencv and python-teressact and run OCR.py. This is my result:

nano@nano-MOV:~$ cd display_ocr-master/
nano@nano-MOV:~/display_ocr-master$ python OCR.py 
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
VIDIOC_QUERYMENU: Invalid argument
Error opening data file ./tessdata/letsgodigital.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'letsgodigital'
Tesseract couldn't load any languages!

the program is going on but when i want to select a region the application stop:

Traceback (most recent call last):
  File "OCR.py", line 203, in <module>
    Recognize(iplimage)
  File "OCR.py", line 39, in Recognize
    full_text = api.GetUTF8Text()
  File "/usr/lib/python2.7/dist-packages/tesseract.py", line 10556, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, TessBaseAPI, name)
  File "/usr/lib/python2.7/dist-packages/tesseract.py", line 57, in _swig_getattr
    raise AttributeError(name)
AttributeError: GetUTF8Text

**Comment by arturaugusto** [comment]
You need to copy the content of `letsgodigital` folder to your `TESSDATA` path.
At my ubuntu system, it's located on `/usr/share/tesseract-ocr/tessdata`

**Comment by arturaugusto** [comment]
@nanomoretti, are you still having issues?

**Comment by nanomoretti** [comment]
yes i am, thanks @arturaugusto. I will try again on a clean virtual machine and then I'll tell you what happens ;)
